### ISSUE TITLE
deployment descriptor missing

### ISSUE THREAD

**Issue by ghost** [DEEZZU/Automatic-Question-Paper-Generator-App#3]
I tried to run the project, it shows that deployment descriptor is missing

**Comment by DEEZZU** [comment]
> I tried to run the project, it shows that deployment descriptor is missing

@Rakshya1771 , it is trying to search the WEB-INF folder in the project (this usually happens when u download from git), just right click on the project -> go to properties -> and set the location of WEB-INF folder.
you can refer this video for help : https://www.youtube.com/watch?v=Dx37rTbAk0Q

**Comment by ghost** [comment]
The question paper generation also does.not workSent from my Samsung Galaxy smartphone.
-------- Original message --------From: DEEPTI SHARMA <notifications@github.com> Date: 30/03/2019  1:07 a.m.  (GMT+05:45) To: DEEZZU/Automatic-Question-Paper-Generator-App <Automatic-Question-Paper-Generator-App@noreply.github.com> Cc: "Rakshya K.C." <rakshya1771@gmail.com>, Mention <mention@noreply.github.com> Subject: Re: [DEEZZU/Automatic-Question-Paper-Generator-App] deployment descriptor missing (#3) Closed #3.

—You are receiving this because you were mentioned.Reply to this email directly, view it on GitHub, or mute the thread.
{"api_version":"1.0","publisher":{"api_key":"05dde50f1d1a384dd78767c55493e4bb","name":"GitHub"},"entity":{"external_key":"github/DEEZZU/Automatic-Question-Paper-Generator-App","title":"DEEZZU/Automatic-Question-Paper-Generator-App","subtitle":"GitHub repository","main_image_url":"https://github.githubassets.com/images/email/message_cards/header.png","avatar_image_url":"https://github.githubassets.com/images/email/message_cards/avatar.png","action":{"name":"Open in GitHub","url":"https://github.com/DEEZZU/Automatic-Question-Paper-Generator-App"}},"updates":{"snippets":[{"icon":"DESCRIPTION","message":"Closed #3."}],"action":{"name":"View Issue","url":"https://github.com/DEEZZU/Automatic-Question-Paper-Generator-App/issues/3#event-2240222413"}}}
[
{
"@context": "http://schema.org",
"@type": "EmailMessage",
"potentialAction": {
"@type": "ViewAction",
"target": "https://github.com/DEEZZU/Automatic-Question-Paper-Generator-App/issues/3#event-2240222413",
"url": "https://github.com/DEEZZU/Automatic-Question-Paper-Generator-App/issues/3#event-2240222413",
"name": "View Issue"
},
"description": "View this Issue on GitHub",
"publisher": {
"@type": "Organization",
"name": "GitHub",
"url": "https://github.com"
}
}
]
